annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: '3.14'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: stable
apiVersion: v2
appVersion: 0.22.416
dependencies:
- alias: ''
  condition: ''
  import-values: []
  name: common
  repository: oci://tccr.io/truecharts
  tags: []
  version: 23.0.10
deprecated: false
description: API Support for your favorite torrent trackers.
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.webp
keywords:
- jackett
- torrent
- usenet
kubeVersion: '>=1.24.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: jackett
sources:
- https://ghcr.io/geek-cookbook/jackett
- https://github.com/Jackett/Jackett
- https://github.com/geek-cookbook/containers/pkgs/container/jackett
- https://github.com/truecharts/charts/tree/master/charts/stable/jackett
type: application
version: 24.0.76
