image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/recyclarr/recyclarr
  tag: 7.2.1
persistence:
  config:
    enabled: true
    mountPath: /config
    targetSelectAll: true
portal:
  open:
    enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CRON_SCHEDULE: '@daily'
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
      initContainers:
        initconfig:
          command:
          - recyclarr
          - config
          - create
          enabled: true
          imageSelector: image
          type: install
