image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/elfhosted/jackett
  tag: 0.22.442
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 9117
        protocol: http
        targetPort: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /health
            readiness:
              path: /health
            startup:
              path: /health
